# Ejemplos de Operaciones con Matrices y Vectores en Numpy

In [ ]:
import numpy as np

In [21]:
w = np.array([1,2])
X = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 10, 10])
print('Vector w:')
print(w)
print('Vector w transpuesto')
print(w.transpose())
print('Matriz X')
print(X)
print('Matriz X transpuesta:')
print(X.transpose())
print('Resultado de la operación:')
Z = np.dot(w, X) + B
print(Z)

Vector w:
[1 2]
Vector w transpuesto
[1 2]
Matriz X
[[1 2 3]
 [4 5 6]]
Matriz X transpuesta:
[[1 4]
 [2 5]
 [3 6]]
Resultado de la operación:
[19 22 25]
